#!/bin/bash
# Test which Simple Icons actually exist

icons=(
  "snowflake"
  "amazonredshift"
  "googlebigquery"
  "microsoftazure"
  "databricks"
  "delta"
  "apacheiceberg"
  "apachehudi"
  "apachedruid"
  "postgresql"
  "mysql"
  "mariadb"
  "oracle"
  "microsoftsqlserver"
  "ibmdb2"
  "teradata"
  "sap"
  "sqlite"
  "presto"
  "trino"
  "clickhouse"
  "amazons3"
  "googlecloud"
  "apachehadoop"
  "minio"
  "cloudflare"
  "backblaze"
  "mongodb"
  "apachecassandra"
  "amazondynamodb"
  "elasticsearch"
  "elastic"
  "apachehbase"
  "couchbase"
  "neo4j"
  "redis"
  "arangodb"
  "apachekafka"
  "rabbitmq"
  "apachepulsar"
  "nats"
  "apacheflink"
  "apachespark"
  "apachehive"
  "salesforce"
  "servicenow"
  "okta"
  "hubspot"
  "stripe"
  "twilio"
  "segment"
  "amplitude"
  "mixpanel"
  "intercom"
  "zendesk"
  "jira"
  "confluence"
  "slack"
  "microsoftteams"
  "tableau"
  "powerbi"
  "looker"
  "qlik"
  "dbt"
  "fivetran"
  "airbyte"
  "talend"
  "informatica"
  "mlflow"
  "tensorflow"
  "pytorch"
  "scikitlearn"
  "keras"
  "jupyter"
  "azuredevops"
  "githubactions"
  "gitlab"
  "jenkins"
  "circleci"
  "travis"
  "docker"
  "kubernetes"
  "helm"
  "terraform"
  "ansible"
  "prometheus"
  "grafana"
  "datadog"
  "splunk"
  "newrelic"
  "pagerduty"
  "git"
  "github"
  "graphql"
  "json"
)

echo "Testing Simple Icons availability..."
echo "===================================="
echo ""

for icon in "${icons[@]}"; do
  status=$(curl -s -o /dev/null -w "%{http_code}" "https://cdn.simpleicons.org/$icon")
  if [ "$status" = "200" ]; then
    echo "✅ $icon"
  else
    echo "❌ $icon ($status)"
  fi
done
